### ISSUE TITLE
double initialized constant SSL_CONFIGURATIONS

### ISSUE THREAD

**Issue by tchun8329** [lostisland/faraday-net_http_persistent#12]
Any way we can have this project use what exists in faraday-1.3.0?

```
/usr/local/bundle/gems/faraday-net_http_persistent-1.2.0/lib/faraday/adapter/net_http_persistent.rb:85: warning: already initialized constant Faraday::Adapter::NetHttpPersistent::SSL_CONFIGURATIONS
/usr/local/bundle/gems/faraday-1.3.0/lib/faraday/adapter/net_http_persistent.rb:66: warning: previous definition of SSL_CONFIGURATIONS was here
```

**Comment by iMacTia** [comment]
Hey @tchun8329, if you're using Faraday 1.3.0 then there's no need to use this gem, as the `Net::HTTP::Persistent` adapter is still bundled with Faraday.
This gem only becomes necessary once you upgrade to [Faraday 1.4.0](https://github.com/lostisland/faraday/releases/tag/v1.4.0).

I'm not really sure why you have it loaded, it may be explicitly on your Gemfile for example, but this is the reason why you're having the issue, as you're effectively loading the adapter file twice.

To solve this, you can either
* keep the Faraday version and remove this gem from the Gemfile, or;
* keep this gem, but upgrade Faraday to v1.4+ (FYI current latest stable is v1.8)
