### ISSUE TITLE
Why is the "Keep-Alive" an integer?

### ISSUE THREAD

**Issue by tdutreui-solocal** [lostisland/faraday-net_http_persistent#18]
Hi,
I observe that this gem generates the following headers in my Rspec VCR cassettes :
```
      Connection:
      - keep-alive
      Keep-Alive:
      - '30'
```
On the other hand, I see in the MDN docs that `Keep-Alive` should be a key/value string.
Could you explain me why?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive

**Comment by iMacTia** [comment]
Hi @tdutreui-solocal we don't set this header in this gem, it gets set somewhere down in the dependencies by either `net-http-persistent` or `net-http`.
You can see in `net-http-persistent` documentation that `30` is the default value: https://github.com/drbrain/net-http-persistent/blob/c1fb1a5ca29c4c2a7102138af22529cc78adb06e/lib/net/http/persistent.rb#L316-L325.

Although I agree with you that the default value should conform to the RFC (assuming the RFC enforces the key/value structure, the MDN docs are not official specifications), but that goes beyond the scope of this gem, so my suggestion is to open an issue against `net-http-persistent` instead.

**Comment by tdutreui-solocal** [comment]
Indeed there is already one https://github.com/drbrain/net-http-persistent/issues/136

**Comment by iMacTia** [comment]
Thank you for sharing the link!
