### ISSUE TITLE
Persistence breaks streaming

### ISSUE THREAD

**Issue by wconrad** [lostisland/faraday-net_http_persistent#5]
## Basic Info

* Faraday Version: 1.5.0
* Ruby Version: ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
* net-http-persistent version: 4.0.1 

## Issue description

Persistence appears to breaks streaming.  Specifically, If the net_http_persistent_adapter is used as in [this example](https://lostisland.github.io/faraday/adapters/net-http-persistent), then a streaming get as shown in [this example](https://lostisland.github.io/faraday/usage/streaming) does not call its on_data procedure.

## Steps to reproduce

```
require "faraday"

connection = Faraday.new("https://google.com") do |f|
  f.adapter :net_http_persistent
end

connection.get("/") do |request|
  request.options.on_data = Proc.new do |chunk, overall_received_bytes|
    puts "Received #{overall_received_bytes} characters"
  end
end
```

The expected output is "Received 220 characters", but instead there is no output.

## Additional info

Gist with scripts to reproduce the problem: https://gist.github.com/wconrad/c6885b2a6dd6494880964c3d6fb8e1f1

**Comment by MikeRogers0** [comment]
> At this point, I'm a bit unsure if this is expected or not, because other adapters present a warning message where streaming is not supported, but it seems like net_http_persistent doesn't.

https://github.com/lostisland/faraday-em_synchrony/blob/ea5dd3f4ca0f5b60fc26eaeda044bf67e4f20ebb/lib/faraday/adapter/em_synchrony.rb#L94-L97

@iMacTia - Maybe the solution is something like below being added to ( https://github.com/lostisland/faraday-net_http_persistent/blob/main/lib/faraday/adapter/net_http_persistent.rb ):

```ruby
def call(env)
  if env[:request]).stream_response?
    warn "Streaming downloads for #{self.class.name} " 'are not yet implemented.'
  end
  
  super
end
```

Would work in the short term? :)

**Comment by iMacTia** [comment]
I think it would be perfect in the short term, unless adding streaming support is a really quick job.
We already have a [streaming tests feature](https://github.com/lostisland/faraday/blob/21ac595919b0372b41386ae00640e16f73a20d31/spec/support/shared_examples/request_method.rb#L164) available from Faraday, which could be easily enabled in this gem's test suite if you already have an implementation in mind.
